# Generated by Django 5.2.6 on 2025-09-22 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Expenses', '0002_rename_expense_expenses'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expenses',
            name='title',
        ),
        migrations.AddField(
            model_name='expenses',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='expenses/'),
        ),
        migrations.AddField(
            model_name='expenses',
            name='merchant',
            field=models.CharField(default='Unknown', max_length=255),
        ),
        migrations.AlterField(
            model_name='expenses',
            name='amount',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='expenses',
            name='category',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='expenses',
            name='date',
            field=models.DateField(),
        ),
    ]
